/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */
/*
 * Committed as the authoritative type surface for @pleaseai/csp-sdk. `napi
 * build` regenerates this file from crates/csp-node/src/lib.rs; keep the two in
 * sync (a build overwrites this with the same shape).
 */

export const enum ContentType {
  Code = 0,
  Docs = 1,
  Config = 2
}
export interface LoadOptions {
  /** Path to a Model2Vec model directory; omit to use the bundled default. */
  modelPath?: string
  /** Content types to index; omit for the default set. */
  content?: Array<ContentType>
}
export interface QueryOptions {
  /** Maximum number of results to return. */
  topK?: number
  /** Restrict results to these languages. */
  filterLanguages?: Array<string>
  /** Restrict results to chunks whose path matches one of these substrings. */
  filterPaths?: Array<string>
}
export interface Chunk {
  content: string
  filePath: string
  startLine: number
  endLine: number
  language?: string
  /** `filePath:startLine-endLine`. */
  location: string
}
export interface SearchResult {
  chunk: Chunk
  score: number
}
export interface IndexStats {
  indexedFiles: number
  totalChunks: number
  /** language → chunk count. */
  languages: Record<string, number>
}
/** Hybrid (dense + BM25) code-search index. */
export class CspIndex {
  /** Build an index from a local directory. */
  static fromPath(path: string, options?: LoadOptions | undefined | null): CspIndex
  /** Build an index from a remote git URL (shallow clone into a temp dir). */
  static fromGit(url: string, options?: LoadOptions | undefined | null, gitRef?: string | undefined | null): CspIndex
  /** Load an index previously persisted with `save`. */
  static loadFromDisk(dir: string): CspIndex
  /** Hybrid search over the indexed chunks. */
  search(query: string, options?: QueryOptions | undefined | null): Array<SearchResult>
  /** Find chunks similar to a seed chunk, excluding the seed itself. */
  findRelated(seed: Chunk, options?: QueryOptions | undefined | null): Array<SearchResult>
  /** Persist the index to a directory. */
  save(dir: string, contentHash?: string | undefined | null): void
  /** Aggregate index statistics. */
  stats(): IndexStats
}
