// Port of src/semble/index/files.py

export type ContentType = 'code' | 'docs' | 'config'

export const EXTENSION_TO_LANGUAGE: Record<string, string> = {
  '.4th': 'forth',
  '.ada': 'ada',
  '.adb': 'ada',
  '.adoc': 'asciidoc',
  '.ads': 'ada',
  '.agda': 'agda',
  '.al': 'al',
  '.as': 'actionscript',
  '.asciidoc': 'asciidoc',
  '.asm': 'asm',
  '.astro': 'astro',
  '.awk': 'awk',
  '.axi': 'netlinx',
  '.axs': 'netlinx',
  '.bash': 'bash',
  '.bat': 'batch',
  '.bb': 'bitbake',
  '.bbappend': 'bitbake',
  '.bbclass': 'bitbake',
  '.beancount': 'beancount',
  '.bib': 'bibtex',
  '.bicep': 'bicep',
  '.blade': 'blade',
  '.bq': 'sql_bigquery',
  '.brs': 'brightscript',
  '.bsl': 'bsl',
  '.bzl': 'starlark',
  '.c': 'c',
  '.c3': 'c3',
  '.c3i': 'c3',
  '.c3t': 'c3',
  '.caddyfile': 'caddy',
  '.cairo': 'cairo',
  '.capnp': 'capnp',
  '.cbl': 'cobol',
  '.cc': 'cpp',
  '.cedar': 'cedar',
  '.cedarschema': 'cedarschema',
  '.cel': 'cel',
  '.cfc': 'cfml',
  '.cfg': 'ini',
  '.chatito': 'chatito',
  '.circom': 'circom',
  '.cjs': 'javascript',
  '.ck': 'chuck',
  '.cl': 'commonlisp',
  '.clar': 'clarity',
  '.clj': 'clojure',
  '.cljc': 'clojure',
  '.cljs': 'clojure',
  '.cls': 'abl',
  '.cmake': 'cmake',
  '.cmd': 'batch',
  '.cob': 'cobol',
  '.cobol': 'cobol',
  '.conf': 'nginx',
  '.cook': 'cooklang',
  '.corn': 'corn',
  '.cpon': 'cpon',
  '.cpp': 'cpp',
  '.cr': 'crystal',
  '.cs': 'csharp',
  '.cshtml': 'razor',
  '.css': 'css',
  '.cst': 'cst',
  '.csv': 'csv',
  '.cts': 'typescript',
  '.cu': 'cuda',
  '.cuda': 'cuda',
  '.cue': 'cue',
  '.cxx': 'cpp',
  '.cylc': 'cylc',
  '.d': 'd',
  '.dart': 'dart',
  '.desktop': 'desktop',
  '.dhall': 'dhall',
  '.diff': 'diff',
  '.dj': 'djot',
  '.dl': 'souffle',
  '.dockerfile': 'dockerfile',
  '.dot': 'dot',
  '.dsp': 'faust',
  '.dtd': 'dtd',
  '.dts': 'devicetree',
  '.dtsi': 'devicetree',
  '.ebnf': 'ebnf',
  '.eds': 'eds',
  '.eex': 'eex',
  '.el': 'elisp',
  '.elm': 'elm',
  '.elv': 'elvish',
  '.enforce': 'enforce',
  '.eps': 'postscript',
  '.erb': 'embeddedtemplate',
  '.erl': 'erlang',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.f': 'fortran',
  '.f03': 'fortran',
  '.f08': 'fortran',
  '.f90': 'fortran',
  '.f95': 'fortran',
  '.fc': 'func',
  '.fidl': 'fidl',
  '.filter': 'poe_filter',
  '.fir': 'firrtl',
  '.fish': 'fish',
  '.fnl': 'fennel',
  '.fs': 'fsharp',
  '.fsd': 'facility',
  '.fsi': 'fsharp_signature',
  '.fsx': 'fsharp',
  '.fth': 'forth',
  '.fun': 'sml',
  '.g': 'gap',
  '.gd': 'gdscript',
  '.gdshader': 'gdshader',
  '.gi': 'gap',
  '.gitattributes': 'gitattributes',
  '.gitignore': 'gitignore',
  '.gleam': 'gleam',
  '.glsl': 'glsl',
  '.gn': 'gn',
  '.gni': 'gn',
  '.gnuplot': 'gnuplot',
  '.go': 'go',
  '.gotmpl': 'gotmpl',
  '.gp': 'gnuplot',
  '.gql': 'graphql',
  '.gradle': 'groovy',
  '.graphql': 'graphql',
  '.gren': 'gren',
  '.groovy': 'groovy',
  '.gv': 'dot',
  '.h': 'c',
  '.hack': 'hack',
  '.hare': 'hare',
  '.hbs': 'glimmer',
  '.hcl': 'hcl',
  '.heex': 'heex',
  '.hjson': 'hjson',
  '.hlsl': 'hlsl',
  '.hocon': 'hocon',
  '.hoon': 'hoon',
  '.hpp': 'cpp',
  '.hrl': 'erlang',
  '.hs': 'haskell',
  '.htm': 'html',
  '.html': 'html',
  '.http': 'http',
  '.hurl': 'hurl',
  '.hx': 'haxe',
  '.hxx': 'cpp',
  '.idr': 'idris',
  '.inc': 'sourcepawn',
  '.ini': 'ini',
  '.ino': 'arduino',
  '.ispc': 'ispc',
  '.j2': 'jinja2',
  '.jai': 'jai',
  '.janet': 'janet',
  '.java': 'java',
  '.jinja2': 'jinja2',
  '.jl': 'julia',
  '.journal': 'ledger',
  '.jq': 'jq',
  '.js': 'javascript',
  '.json': 'json',
  '.json5': 'json5',
  '.jsonnet': 'jsonnet',
  '.jsx': 'javascript',
  '.just': 'just',
  '.k': 'kcl',
  '.kdl': 'kdl',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.lc': 'elsa',
  '.ldg': 'ledger',
  '.lds': 'linkerscript',
  '.lean': 'lean',
  '.ledger': 'ledger',
  '.leex': 'eex',
  '.less': 'less',
  '.libsonnet': 'jsonnet',
  '.liquid': 'liquid',
  '.lisp': 'commonlisp',
  '.ll': 'llvm',
  '.lua': 'lua',
  '.luau': 'luau',
  '.m': 'objc',
  '.magik': 'magik',
  '.makefile': 'make',
  '.markdown': 'markdown',
  '.matlab': 'matlab',
  '.md': 'markdown',
  '.mermaid': 'mermaid',
  '.meson': 'meson',
  '.mjs': 'javascript',
  '.mk': 'make',
  '.ml': 'ocaml',
  '.mli': 'ocaml_interface',
  '.mlir': 'mlir',
  '.mll': 'ocamllex',
  '.mmd': 'mermaid',
  '.mod': 'gomod',
  '.mojo': 'mojo',
  '.move': 'move',
  '.mts': 'typescript',
  '.nasm': 'nasm',
  '.ncl': 'nickel',
  '.nginx': 'nginx',
  '.nim': 'nim',
  '.nims': 'nim',
  '.ninja': 'ninja',
  '.nix': 'nix',
  '.norg': 'norg',
  '.nqc': 'nqc',
  '.nu': 'nushell',
  '.nut': 'squirrel',
  '.odin': 'odin',
  '.org': 'org',
  '.p': 'abl',
  '.pas': 'pascal',
  '.patch': 'diff',
  '.pbtxt': 'textproto',
  '.pem': 'pem',
  '.pgn': 'pgn',
  '.php': 'php',
  '.pkl': 'pkl',
  '.pl': 'perl',
  '.plt': 'gnuplot',
  '.pm': 'perl',
  '.po': 'po',
  '.pony': 'pony',
  '.pot': 'po',
  '.pp': 'puppet',
  '.prisma': 'prisma',
  '.pro': 'prolog',
  '.promql': 'promql',
  '.properties': 'properties',
  '.proto': 'proto',
  '.prql': 'prql',
  '.ps': 'postscript',
  '.ps1': 'powershell',
  '.psd1': 'powershell',
  '.psm1': 'powershell',
  '.psv': 'psv',
  '.pug': 'pug',
  '.purs': 'purescript',
  '.py': 'python',
  '.pyi': 'python',
  '.pyw': 'python',
  '.ql': 'ql',
  '.qml': 'qmljs',
  '.r': 'r',
  '.rasi': 'rasi',
  '.razor': 'razor',
  '.rb': 'ruby',
  '.rbs': 'rbs',
  '.re': 're2c',
  '.rego': 'rego',
  '.res': 'rescript',
  '.resi': 'rescript',
  '.rkt': 'racket',
  '.robot': 'robot',
  '.roc': 'roc',
  '.ron': 'ron',
  '.rs': 'rust',
  '.rst': 'rst',
  '.rtf': 'rtf',
  '.s': 'asm',
  '.scad': 'openscad',
  '.scala': 'scala',
  '.scm': 'scheme',
  '.scss': 'scss',
  '.sh': 'bash',
  '.shtml': 'superhtml',
  '.sig': 'sml',
  '.slang': 'slang',
  '.smali': 'smali',
  '.smithy': 'smithy',
  '.smk': 'snakemake',
  '.sml': 'sml',
  '.sol': 'solidity',
  '.sp': 'sourcepawn',
  '.sparql': 'sparql',
  '.sql': 'sql',
  '.squirrel': 'squirrel',
  '.st': 'smalltalk',
  '.stan': 'stan',
  '.star': 'starlark',
  '.sv': 'systemverilog',
  '.svelte': 'svelte',
  '.svh': 'systemverilog',
  '.sw': 'sway',
  '.swift': 'swift',
  '.tact': 'tact',
  '.tal': 'uxntal',
  '.tape': 'vhs',
  '.tcl': 'tcl',
  '.td': 'tablegen',
  '.templ': 'templ',
  '.tera': 'tera',
  '.tex': 'latex',
  '.textproto': 'textproto',
  '.tf': 'terraform',
  '.tfvars': 'terraform',
  '.thrift': 'thrift',
  '.tl': 'teal',
  '.tla': 'tlaplus',
  '.todotxt': 'todotxt',
  '.toml': 'toml',
  '.tres': 'godot_resource',
  '.trigger': 'apex',
  '.ts': 'typescript',
  '.tscn': 'godot_resource',
  '.tsconfig': 'typoscript',
  '.tsp': 'typespec',
  '.tsv': 'tsv',
  '.tsx': 'tsx',
  '.ttl': 'turtle',
  '.twig': 'twig',
  // Overly broad
  // '.txt': 'vimdoc',
  '.typoscript': 'typoscript',
  '.typst': 'typst',
  '.v': 'v',
  '.vb': 'vb',
  '.verilog': 'verilog',
  '.vhd': 'vhdl',
  '.vhdl': 'vhdl',
  '.vim': 'vim',
  '.vrl': 'vrl',
  '.vue': 'vue',
  '.w': 'abl',
  '.wast': 'wast',
  '.wat': 'wat',
  '.wgsl': 'wgsl',
  '.wit': 'wit',
  '.wl': 'wolfram',
  '.xml': 'xml',
  '.xsl': 'xml',
  '.xslt': 'xml',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.yuck': 'yuck',
  '.zig': 'zig',
  '.ziggy': 'ziggy',
  '.zsh': 'zsh',
}

export const DOC_LANGUAGES: ReadonlySet<string> = new Set([
  'asciidoc',
  'bibtex',
  'djot',
  'doxygen',
  'html',
  'javadoc',
  'jsdoc',
  'latex',
  'luadoc',
  'markdown',
  'markdown_inline',
  'mermaid',
  'norg',
  'norg_meta',
  'org',
  'phpdoc',
  'po',
  'rst',
  'rtf',
  'vimdoc',
])

export const CONFIG_LANGUAGES: ReadonlySet<string> = new Set([
  'beancount',
  'capnp',
  'cedarschema',
  'comment',
  'cooklang',
  'cpon',
  'desktop',
  'devicetree',
  'diff',
  'dtd',
  'editorconfig',
  'ebnf',
  'git_config',
  'gitattributes',
  'gitcommit',
  'gitignore',
  'godot_resource',
  'gomod',
  'gosum',
  'gowork',
  'gpg',
  'hjson',
  'hocon',
  'ini',
  'kdl',
  'ledger',
  'pem',
  'pgn',
  'properties',
  'proto',
  'requirements',
  'ron',
  'smithy',
  'ssh_config',
  'textproto',
  'thrift',
  'todotxt',
  'toml',
  'turtle',
  'typespec',
  'wit',
  'xcompose',
  'xml',
  'yaml',
  'ziggy_schema',
])

export const DATA_LANGUAGES: ReadonlySet<string> = new Set([
  'csv',
  'json',
  'json5',
  'psv',
  'tsv',
])

export const ALL_LANGUAGES: ReadonlySet<string> = new Set(
  Object.values(EXTENSION_TO_LANGUAGE),
)

// Code languages = ALL - DOC - CONFIG - DATA
const CODE_LANGUAGES: ReadonlySet<string> = (() => {
  const set = new Set<string>(ALL_LANGUAGES)
  for (const l of DOC_LANGUAGES) {
    set.delete(l)
  }
  for (const l of CONFIG_LANGUAGES) {
    set.delete(l)
  }
  for (const l of DATA_LANGUAGES) {
    set.delete(l)
  }
  return set
})()

// Invert EXTENSION_TO_LANGUAGE, collecting duplicates per language.
const LANGUAGE_TO_EXTENSIONS: ReadonlyMap<string, readonly string[]> = (() => {
  const inv = new Map<string, string[]>()
  for (const [ext, lang] of Object.entries(EXTENSION_TO_LANGUAGE)) {
    const list = inv.get(lang)
    if (list === undefined) {
      inv.set(lang, [ext])
    }
    else { list.push(ext) }
  }
  return inv
})()

const CONTENT_TYPE_LANGUAGES: Record<ContentType, ReadonlySet<string>> = {
  code: CODE_LANGUAGES,
  docs: DOC_LANGUAGES,
  config: CONFIG_LANGUAGES,
}

/**
 * Detect the language of a file by its extension.
 *
 * Matching is case-insensitive on the final `.suffix` (mirroring Python's
 * `Path(...).suffix.lower()` lookup).
 */
export function detectLanguage(fileName: string): string | undefined {
  // Mirror Python's Path(fileName).suffix.lower(): take the substring after
  // the last path separator, then return the part from the final '.' onward —
  // but only if that '.' is not at the very start of the basename (so
  // '.gitignore' resolves to '' just like Python). Both POSIX ('/') and
  // Windows ('\\') separators are handled, matching pathlib.Path on Windows.
  const lastSep = Math.max(fileName.lastIndexOf('/'), fileName.lastIndexOf('\\'))
  const base = fileName.slice(lastSep + 1)
  const dot = base.lastIndexOf('.')
  if (dot <= 0) {
    return undefined
  }
  return EXTENSION_TO_LANGUAGE[base.slice(dot).toLowerCase()]
}

/**
 * Resolve a set of content types to the union of file extensions associated
 * with their languages. Optional `extensions` are added verbatim. The result
 * is sorted lexicographically (mirroring Python's `sorted(set)`).
 */
export function getExtensions(
  types: readonly ContentType[],
  extensions: readonly string[] | undefined,
): string[] {
  const languages = new Set<string>()
  for (const type of types) {
    for (const lang of CONTENT_TYPE_LANGUAGES[type]) {
      languages.add(lang)
    }
  }
  const out = new Set<string>()
  for (const lang of languages) {
    const exts = LANGUAGE_TO_EXTENSIONS.get(lang)
    if (exts === undefined) {
      continue
    }
    for (const ext of exts) {
      out.add(ext)
    }
  }
  if (extensions !== undefined) {
    for (const ext of extensions) {
      out.add(ext)
    }
  }
  return [...out].sort()
}
